### ISSUE TITLE
Install option not working. 

### ISSUE THREAD

**Issue by stefanrijn** [khmyznikov/pwa-install#14]
The installation buttons don't seem to work anymore. The "show" options popup, but when you click on the install button, nothing seems to happen.

**Comment by khmyznikov** [comment]
Hi! Can you check this here https://www.khmyznikov.com/pwa-install/ and maybe record your screen or write clear steps to reproduce? Do you have any errors in console?

**Comment by stefanrijn** [comment]
Hi,

Thanks for getting back to me on this. I added a screenshot to clarify the issue. When I click on the installation buttons, the app is not installed. Nothing happens. No errors show up in the console. It seems that the action is not being triggered.

![Screenshot 2023-01-03 at 15 05 48](https://user-images.githubusercontent.com/17291136/210374308-22725ea6-3063-44af-894a-806d9d90f7cf.png)

**Comment by ThaDaVos** [comment]
Just my two-cents on thsi:

I just tested with Microsoft Edge - and it really doesn't work but I noticed that is after one switches windows (so one application to another) and after that comes back, then install doesn't seem to work (at least for me) - I guess the implementation is based on the `BeforeInstallPromptEvent` event thing - noticed this also works differently in Microsoft Edge - it is fired when the application get's focus after loading the page - maybe because the pop-up is already open, the variable/event isn't updated/catched correctly.

Is it Edge or Chrome being shown @stefanrijn ?
