### ISSUE TITLE
[Question] Typescript Support for React Proxy

### ISSUE THREAD

**Issue by spencerdezartsmith** [khmyznikov/pwa-install#46]
Do you have support for typescript that is available for the React Proxy you have provided?

Thanks!

**Comment by lnhrdt** [comment]
I found this issue looking for the same thing.

[The docs](https://github.com/khmyznikov/pwa-install?tab=readme-ov-file#use) suggest importing the wrapper using `import PWAInstall from '@khmyznikov/pwa-install/dist/pwa-install.react.js'` and there's no type definitions.

I see the react wrapper is declared in [src/fallback/react.ts](https://github.com/khmyznikov/pwa-install/blob/main/src/fallback/react.ts) but it doesn't seem to be exported properly in [index.ts](https://github.com/khmyznikov/pwa-install/blob/main/src/index.ts). I also see the TypeScript source files are surprisingly included in the bundle but when I tried to import them directly using `import PWAInstall from '@khmyznikov/pwa-install/src/fallback/react'` the result is of type `any`.

@spencerdezartsmith I see you marked this as completed, did you find a solution?

**Comment by khmyznikov** [comment]
@lnhrdt for react wrapper this types was generated https://github.com/khmyznikov/pwa-install/blob/main/dist/types/fallback/react.d.ts

**Comment by anilanar** [comment]
@khmyznikov I suggest you try using this package on codesandbox with react+typescript template and see why it doesn't work. You either need to adapt package.json and define multiple `exports` like https://www.kravchyk.com/typescript-npm-package-json-exports/ or you need to move files in `dist` in such a way that `react.js` and `react.d.ts` are in the same directory so that something like `import PWAInstall from '@khmyznikov/pwa-install/dist/react'` works.

**Comment by khmyznikov** [comment]
@anilanar thanks for hints. I have changed how the react wrapper is built, can you try to use latest commit like this in package.json: `"@khmyznikov/pwa-install": "github:khmyznikov/pwa-install"` and check how it works for you?
@lnhrdt @spencerdezartsmith also calling you to help verify the fix.

**Comment by khmyznikov** [comment]
@anilanar should be doable. But, even "new" node16 security support ended 8 months ago. It's actually old 😅

**Comment by anilanar** [comment]
@khmyznikov You are totally right but... Listen to me for a moment 😄 

Most FE projects are single-page apps and use just a bundler like webpack or vite with ES modules. They don't use node.js runtime. 
Node.js implemented ESMs with their own "flavor" that contradicted all existing code that used ES modules. All imports must contain the file extension like `import foo from './foo.js'`. Typescript, years later, added support for that with a big **BUT**: you need to import ts files with a js extension. So if you have `foo.ts`, it must be imported like `import foo from './foo.js'`. With TS 5, they tried to fix that by introducing `moduleResolution: bundler`. Now you can import either without extensions or with a ts extension, again a big **BUT**, you cannot use async imports! It doesn't end there and there are even more problems, but this should be sufficient for convincing 😃 

Therefore, most FE code bases still use `moduleResolution: node` because there's no reason to use something else, at least for now. In future, if libraries start replacing `main`, `module`, `types` fields with `exports`, then yes, everybody will have to play along.

**Comment by khmyznikov** [comment]
@anilanar can you check again for moduleResolution: node ? Works ok on my test project.

**Comment by khmyznikov** [comment]
I think the react types finally fixed

**Comment by anilanar** [comment]
I'll work on this area again this week, I'll give it a try 👍

**Comment by khmyznikov** [comment]
@anilanar wrapper code shouldn't be needed.
```typescript
import React, { useEffect, useRef, useState } from 'react';

import PWAInstall from '@khmyznikov/pwa-install/react-legacy';
import { PWAInstallElement } from '@khmyznikov/pwa-install';

function App() {
  const appName = 'My PWA';

  const [promptEvent, setPromptEvent] = useState(null);
  const pwaInstallRef = useRef<PWAInstallElement>(null);

  useEffect(() => {
      // @ts-ignore
    let lastPromptEvent = window.promptEvent;

    const intervalId = setInterval(() => {
        // @ts-ignore
      if (window.promptEvent !== lastPromptEvent) {
          // @ts-ignore
        lastPromptEvent = window.promptEvent;
          // @ts-ignore
        setPromptEvent(window.promptEvent); // Update state with new value
      }
    }, 100); // Check every 100ms

    // Cleanup interval on component unmount
    return () => {
      clearInterval(intervalId);
    };
  }, []);

  return (
    <div className="App">
      <header className="App-header">
 
        <button onClick={() => pwaInstallRef.current?.install()}>Install</button>
        <button onClick={() => pwaInstallRef.current?.hideDialog()}>Hide</button>
        <button onClick={() => pwaInstallRef.current?.showDialog(true)}>Show</button>

        <PWAInstall ref={pwaInstallRef} externalPromptEvent={promptEvent} name={appName} onPwaInstallAvailableEvent={(event) => console.log(event)}></PWAInstall>
      </header>
    </div>
  );
}

export default App;
```

Sample with externalPromptEvent in async mode.

**Comment by anilanar** [comment]
@khmyznikov Sadly it doesn't work.

Here's a repro I initialized with `tsc --init` and `npm init -y` and just changed `module` to `esnext` and `moduleResolution` to `node`.

**Comment by khmyznikov** [comment]
@anilanar not sure how to fix old module resolution. Here's a fully working sample: https://stackblitz.com/edit/vite-react-ts-2eeiak?file=src%2FApp.tsx

**Comment by iwgx-kargo** [comment]
Also got this import issue, seems fine if you use React + TS project

but no luck if you still use JS (which is still many project do), see this minimal repro https://stackblitz.com/edit/vitejs-vite-l7d8d6?file=src%2FApp.jsx
